---
title: "06_dydid"
author: Tyler L. McIntosh
date: last-modified
format:
  html:
    embed-resources: true
    html-math-method: katex
    css: styles.css
    toc: true
    toc-depth: 1
    toc-title: Contents
    toc-location: right
    code-fold: true
    code-summary: "Show the code"
---


# Setup for analysis

``` {r setupchunk}
#| echo: true
#| message: false
#| warning: false
#| results: 'hide'

rm(list = ls())

if(!requireNamespace("here", quietly = TRUE)) {
  install.packages("here")
}
library(here)

source(here::here("utils", "functions.R"))

install_load_packages(c(
  "tidyverse",
  "tictoc",
  "hstats",
  "glue",
  "shapviz",
  "patchwork",
  "cobalt",
  "purrr",
  "corrplot",
  "gridExtra",
  "tictoc",
  "fect",
  "fixest",
  "did",
  "arrow",
  "panelView",
  "PanelMatch",
  "bacondecomp",
  "didimputation",
  "doParallel",
  "HonestDid",
  "HonestDidFEct",
  "DIDmultiplegtDYN",
  "sf",
  "spdep",
  "purrr",
  "gstat",
  "scales",
  "broom",
  "ggfixest"))

dir_figs <- here::here('figs')
#dir_derived <- here::here('data', 'derived', 'GEE_Exports_resilience_20260218')
dir_derived <- here::here('data', 'derived', 'idb_500_20251130')
dir_raw <- here::here('data', 'raw')
dir_manual <- here::here('data', 'manual')
dir_ensure(c(dir_figs,
             dir_derived,
             dir_manual,
             dir_raw))

seed = 1234
set.seed(seed)


```

#

```{r}
  
#dats_long <- arrow::read_parquet(here(dir_derived, "all_dats_long.parquet"))
dats_long <- arrow::read_parquet(here(dir_derived, "test_dats_long.parquet"))


# dats_long_f <- dats_long |>
#   select(uniqueID, year, rap_tree, vcf_tree, lat, long, 
#          #ecoregion_short_name,
#          biotic_5_yrs_prior_sum, biotic, pdsi_annual, pdsi_annual_5_yrs_prior_sum, fire, treated)


# Set cohorts
dats_long_did <- get.cohort(dats_long, D = "treated",
                                 index = c("uniqueID", "year"),
                                 start0 = TRUE)
dats_long_did[which(is.na(dats_long_did$FirstTreat)),"FirstTreat"] <- 1000 


set_cd_groups <- function(df, b_threshold, d_threshold) {
  df_new <- df |>
    mutate(cd_group = case_when(biotic_5_yrs_prior_sum < b_threshold & 
                                  fire == 1 & 
                                  pdsi_annual_5_yrs_prior_sum > d_threshold ~ "f",
                                biotic_5_yrs_prior_sum >= b_threshold & 
                                  fire == 1 & 
                                  pdsi_annual_5_yrs_prior_sum > d_threshold ~ "bf",
                                biotic_5_yrs_prior_sum < b_threshold &
                                  fire == 1 & 
                                  pdsi_annual_5_yrs_prior_sum <= d_threshold ~ "df",
                                biotic_5_yrs_prior_sum >= b_threshold &
                                  fire == 1 & 
                                  pdsi_annual_5_yrs_prior_sum <= d_threshold ~ "bdf",
                                TRUE ~ NA))
  return(df_new)
}

dats_use <- set_cd_groups(df = dats_long_did, b_threshold = 10, d_threshold = -10)

unique(dats_use$cd_group)
#hist(dats_long$pdsi_annual_5_yrs_after_sum)

```




# new code for setting groups

```{r}

set_cd_groups <- function(df,
                          b_nm,
                          d_nm,
                          cd_nm,
                          b_threshold,
                          d_threshold) {
  df_new <- df |>
    dplyr::mutate(
      "{cd_nm}" := dplyr::case_when(
        .data[[b_nm]] <  b_threshold & fire == 1 & .data[[d_nm]] >  d_threshold ~ "f",
        .data[[b_nm]] >= b_threshold & fire == 1 & .data[[d_nm]] >  d_threshold ~ "bf",
        .data[[b_nm]] <  b_threshold & fire == 1 & .data[[d_nm]] <= d_threshold ~ "df",
        .data[[b_nm]] >= b_threshold & fire == 1 & .data[[d_nm]] <= d_threshold ~ "bdf",
        TRUE ~ NA_character_
      )
    )
  
  return(df_new)
}


d <- set_cd_groups(df = d,
                   b_nm = "biotic_relaxedforestnorm_5_yrs_prior_sum_yot",
                   d_nm = "pdsi_annual_5_yrs_prior_threshold_n4_yot",
                   cd_nm = "cd_group_b10_pdsin4t1",
                   b_threshold = 10,
                   d_threshold = 1)

d <- set_cd_groups(df = d,
                   b_nm = "biotic_relaxedforestnorm_5_yrs_prior_sum_yot",
                   d_nm = "pdsi_annual_5_yrs_prior_threshold_n3_yot",
                   cd_nm = "cd_group_b10_pdsin3t1",
                   b_threshold = 10,
                   d_threshold = 1)

d <- set_cd_groups(df = d,
                   b_nm = "biotic_relaxedforestnorm_5_yrs_prior_sum_yot",
                   d_nm = "pdsi_annual_5_yrs_prior_threshold_n3_yot",
                   cd_nm = "cd_group_b10_pdsin4t3",
                   b_threshold = 10,
                   d_threshold = 3)


```




# Test spatial cutoffs - LATER

```{}


```


# Wrapper functions
```{r}

# This function runs a feols analysis on dataframe df using ref_period.
# It will compute the model using all 0 values in trt_col (treatment column) as the control and all 1 values in trt_col with grp in subgrp_col as the estimating group 
feols_trt_subg <- function(subgrp_col,
                              grp,
                              trt_col = "fire",
                              df,
                              ...) {
  # Convert string to symbol
  col_sym <- sym(subgrp_col)
  trt_col_sym <- sym(trt_col)
  
  df_never_trt <- df |>
    filter(!!trt_col_sym == 0)
  
  df_subset <- df |>
    filter(!!trt_col_sym == 1 & !!col_sym == grp)
  
  df_use <- bind_rows(df_never_trt, df_subset)

  model <- feols(
    data = df_use,
    ...
  )
  
  n_treated_subgroup_units <- length(unique(df_subset$uniqueID))
  n_never_treated_units <- length(unique(df_never_trt$uniqueID))
  attr(model, "n_treated_subgroup_units") <- n_treated_subgroup_units
  attr(model, "n_never_treated_units") <- n_never_treated_units
  
  return(model)
}


feols_multi_trt <- function(subgrp_col,
                            df,
                            groups = NULL,
                            trt_col,
                            ...) {

  if (is.null(groups)) {
    groups <- sort(unique(df[[subgrp_col]]))
    groups <- groups[!is.na(groups)]
  }

  models <- purrr::map(groups, \(g) {
    feols_trt_subg(subgrp_col = subgrp_col, grp = g, df = df, trt_col = trt_col, ...)
  })

  names(models) <- groups

  models
}


# Model list and model_labels should be the same length!
# If item in model_list contains attribute "n_treated_subgroup_units", the attribute will be appended to the model name in the legend

plot_sunab_models <- function(model_list,
                              model_labels = NULL,
                              title = "Dynamic-DiD Event-Study Estimates from Multiple Models",
                              ribbon_type = "ribbon", #either "ribbon" or "dashed",
                              caption = "95% confidence intervals shown;\nInteraction-weighted (Sun-Abraham) estimates used;\nConley standard errors with 125km cutoff, 20km pixel",
                              baseline = -1,
                              xlim = c(-10, 20),
                              ylim = c(-50, 50)
                              ) {
  
  # If no labels provided, auto-label as Model 1, Model 2, etc.
  if (is.null(model_labels)) {
    model_labels <- paste0("Model ", seq_along(model_list))
  }
  
  # Extract coefficients for each model and attach model label
  plot_data <- map2_dfr(model_list, model_labels, function(model, label) {
    df <- as.data.frame(as.matrix(model$coeftable))
    df$term <- rownames(model$coeftable)
    
    has_attr <- function(x, attr_name) {
      !is.null(attr(x, attr_name))
    }
    
    if (has_attr(model, "n_treated_subgroup_units")) {
      label <- glue("{label} (N = {attr(model, 'n_treated_subgroup_units')})")
    }
    
    df %>%
      filter(str_detect(term, "^year::")) %>%
      mutate(
        Time = as.numeric(str_extract(term, "-?\\d+")),
        CI_upper = Estimate + 1.96 * `Std. Error`,
        CI_lower = Estimate - 1.96 * `Std. Error`,
        Model = label
      )
  })

  # Plot
  if(ribbon_type == "ribbon") {
    ggplot(plot_data, aes(x = Time, y = Estimate, color = Model, fill = Model)) +
      geom_line(linewidth = 1) +
      geom_point(size = 2) +
      geom_ribbon(aes(ymin = CI_lower, ymax = CI_upper), alpha = 0.2, color = NA) +
      geom_vline(xintercept = baseline, linetype = "dashed", color = "gray40") +
      geom_hline(yintercept = 0, color = "black") +
      labs(
        x = "Event Time",
        y = "Treatment Effect",
        title = title,
        caption = caption
      ) +
      theme_minimal(base_size = 13) +
      theme(legend.position = "bottom")  +
      xlim(xlim)+
      ylim(ylim)
  } else {
    ggplot(plot_data, aes(x = Time, y = Estimate, color = Model)) +
      geom_line(linewidth = 1) +
      geom_point(size = 2) +
      
      # CI as dotted lines instead of ribbon
      geom_line(aes(y = CI_upper), linetype = "dotted", linewidth = 0.8) +
      geom_line(aes(y = CI_lower), linetype = "dotted", linewidth = 0.8) +
      
      geom_vline(xintercept = baseline, linetype = "dashed", color = "gray40") +
      geom_hline(yintercept = 0, color = "black") +
      labs(
        x = "Event Time",
        y = "Treatment Effect",
        title = title,
        caption = caption
      ) +
      theme_minimal(base_size = 13) +
      theme(legend.position = "bottom") +
      xlim(xlim) +
      ylim(ylim)
  }

}



```


# Run models
```{r}

#dt <- dats_use |> slice_sample(n = 1000000)

idb_models <- feols_multi_trt(subgrp_col = "cd_group",
                              df = dats_use,
                              groups = NULL,
                              trt_col = "fire",
                              fml = rap_tree ~ biotic + pdsi_annual + sunab(FirstTreat, year, ref.p = -6) | uniqueID + year,
                              #fml = rap_tree ~ pdsi_annual + sunab(FirstTreat, year, ref.p = -6) | uniqueID + year,
                              mem.clean = TRUE,
                              lean = FALSE,
                              vcov = fixest::vcov_conley(lat = "lat",
                                                         lon = "long",
                                                         cutoff = 125,
                                                         pixel = 20,
                                                         distance = "triangular"
                                                         )
                              )



plot_sunab_models(idb_models,
                  names(idb_models),
                  baseline = -6,
                  xlim = c(-10, 20),
                  ylim = c(-50, 10))

ggplot(dats_use |> filter(cd_group == "bf" | cd_group == "bdf"), aes(biotic_5_yrs_prior_sum)) +
  geom_histogram(bins = 30) +
  facet_wrap(~ cd_group)


```



```{r}


dats_quick <- dats_use |>
  filter(!is.na(cd_group)) |>
  slice_head(n = 100000) |>
  mutate(fire_frg = interaction(burn_sev, frg_reclass_desc),
         fire_pre_drought = interaction(burn_sev, pdsi_annual_5_yrs_prior_threshold),
         fire_pre_drought = interaction(burn_sev, pdsi_annual_5_yrs_after_threshold),
         biotic_cut = cut(biotic,
             breaks = c(0, 20, 40, 60, 80, 100),
             labels = c()
             )
         )

ggplot(dats_quick) +
  geom_smooth(method = 'gam', aes(x = Time_to_Treatment, y = rap_tree, color = cd_group)) +
  xlim(c(-10, 20)) +
  labs(title = "GAM fits sample")

ggplot(dats_quick) +
  geom_smooth(method = 'gam', aes(x = Time_to_Treatment, y = vcf_tree, color = cd_group)) +
  xlim(c(-10, 20)) +
  labs(title = "GAM fits sample")

ggplot(dats_quick |> filter(burn_sev != "Negligible")) +
  geom_smooth(method = 'gam', aes(x = Time_to_Treatment, y = rap_tree, color = frg_reclass_desc, lty = burn_sev)) +
  xlim(c(-10, 20)) +
  labs(title = "GAM fits sample")




```



```{r}
dats_short <- arrow::read_parquet(here(dir_derived, 'test_dats_short.parquet'))

glimpse(dats_short)
```

```{r}


```


<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" >Click to see Session Information</button><div id="collapseOne" class="accordion-collapse collapse"><div>

```{r sessionInfo}
sessionInfo()
```

